# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#


Vagrant.configure("2") do |config|

        (1..3).each do |i|
                config.vm.define "server#{i}" do |client|
                        client.vm.box = "bento/ubuntu-16.04"
                        client.vm.network "private_network", ip: "192.100.50.#{i+1}"
                        client.vm.provision "shell", inline: "apt-get update && apt-get install python-minimal python-pip -y"
               end
        end

end

