Vagrant.configure("2") do |config|
	config.vm.box = "bento/centos-7.2"

	config.vm.define "ipa1" do |node|
		node.vm.provider "virtualbox" do |vbox|
			vbox.memory=2048
		end
		config.vm.provision "ansible" do |ansible|
			ansible.playbook = "config.yml"
			ansible.extra_vars = {host_name: "ipa1", replica: "no"}
			node.vm.network "private_network", ip: "192.100.50.2"
		end
	end
end