# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#

$prov_script = <<SCRIPT
useradd ansible -m -s /bin/bash -G sudo && echo "ansible:Whodis2897!" | chpasswd&& apt-get install python-minimal -y       
SCRIPT


Vagrant.configure("2") do |config|

	config.vm.provider :virtualbox do |vm|
		vm.memory = 4096
                vm.customize ["modifyvm", :id, "--nicpromisc2","allow-all"]
	end 

	config.vm.provider "virtualbox"
	config.vm.box = "ubuntu/xenial64"
	config.vm.network "private_network", ip: "192.56.152.2"

	config.vm.provision "shell", inline: $prov_script
end
