Vagrant.configure("2") do |config|

        (1..1).each do |i|
                config.vm.define "server#{i}" do |client|
                        client.vm.box = "bento/centos-7.3"
                        client.vm.network "private_network", ip: "192.100.50.#{i+1}"
               end
        end

end

