Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    virtualbox.gui = false
  end
  config.vm.box = "mwrock/Windows2016"
  config.vm.network "private_network", type: "dhcp"
  #config.vm.provision "shell", inline: "Enable-PsRemoting -Force"
end

