# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search. 
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    virtualbox.gui = false
  end
  config.vm.box = "mwrock/Windows2012R2"
  config.vm.network "private_network", ip: "192.168.2.2"
  config.vm.provision "shell", inline: "Enable-PSRemoting -Force"
  config.vm.provision "shell", inline: "C:/vagrant/ansible_setup.ps1"
end
