Vagrant.configure("2") do |config|


        config.vm.define "server1" do |client|
        	client.vm.provider "virtualbox" do |vm|
        		vm.memory =  2048
        		vm.cpus = 1
        	end
                client.vm.provision "shell", inline: "hostnamectl set-hostname server1"
                client.vm.box = "bento/centos-stream-9"
                client.vm.network "private_network", ip: "192.168.50.2"
        		client.vm.synced_folder "~/git", "/git"
        end
        config.vm.define "server2" do |client|
        	client.vm.provider "virtualbox" do |vm|
        		vm.memory =  2048
        		vm.cpus = 1
        	end
                client.vm.provision "shell", inline: "hostnamectl set-hostname server2"
                client.vm.box = "bento/centos-stream-9"
                client.vm.network "private_network", ip: "192.168.50.3"
        		client.vm.synced_folder "~/git", "/git"
        end

end
